apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    release: prometheus
    app: prometheus-operator
  name: opswatch.acm.rules
  namespace: monitoring
spec:
  groups:
  - name: acm.rules
    rules:
    - alert: AwsCloudwatchAcmCertificateExpirationWarning
      annotations:
        summary: ACM certificate will expire in less than 7 days
        description: ACM certificate will expire in {{$value}} days for arn {{ $labels.dimension_CertificateArn }} in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}
        runbook_url: https://docs.aws.amazon.com/acm/latest/userguide/troubleshooting-renewal.html
      expr: aws_cloudwatch_CertificateManager_DaysToExpiry_CertificateArn{acm_in_use!="0"} < 7
      for: 30m
      labels:
        severity: warning
        asy_itsm_severity: medium
    - alert: AwsCloudwatchAcmCertificateExpirationCritical
      annotations:
        summary: ACM certificate will expire in less than 1 days
        description: ACM certificate will expire in {{$value}} days for arn {{ $labels.dimension_CertificateArn }} in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}
        runbook_url: https://docs.aws.amazon.com/acm/latest/userguide/troubleshooting-renewal.html
      expr: aws_cloudwatch_CertificateManager_DaysToExpiry_CertificateArn{acm_in_use!="0"} <= 1
      for: 15m
      labels:
        severity: critical
        asy_itsm_severity: high
