apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    release: prometheus
    app: prometheus-operator
  name: opswatch.acm.rules
  namespace: monitoring
spec:
  groups:
  - name: acm.rules
    rules:
    - alert: AwsCloudwatchAcmCertificateExpirationWarning
      annotations:
        summary: ACM certificate will expire in less than 30 days
        description: ACM certificate will expire in {{$value}} days for arn {{ $labels.dimension_CertificateArn }} in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}
        runbook_url: https://docs.aws.amazon.com/acm/latest/userguide/troubleshooting-renewal.html
      expr: aws_cloudwatch_CertificateManager_DaysToExpiry_CertificateArn{acm_in_use!="0"} < 30
      for: 30m
      labels:
        severity: warning
    - alert: AwsCloudwatchAcmCertificateExpirationCritical
      annotations:
        summary: ACM certificate will expire in less than 10 days
        description: ACM certificate will expire in {{$value}} days for arn {{ $labels.dimension_CertificateArn }} in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}
        runbook_url: https://docs.aws.amazon.com/acm/latest/userguide/troubleshooting-renewal.html
      expr: aws_cloudwatch_CertificateManager_DaysToExpiry_CertificateArn{acm_in_use!="0"} < 10
      for: 15m
      labels:
        severity: critical
