---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: billing.rules
  namespace: monitoring
spec:
  groups:
  - name: billing.rules # TODO: not part of opswatch
    rules:
    - record: namespace_cpu_requests
      expr: sum(kube_pod_container_resource_requests{resource="cpu"}) by (cluster, namespace, aws_account_id)
    - record: namespace_memory_requests
      expr: sum(kube_pod_container_resource_requests{resource="memory"}) by (cluster, namespace, aws_account_id)
    - record: namespace_memory_usage
      expr: sum(container_memory_usage_bytes) by (cluster, namespace, aws_account_id)
    - record: namespace_cpu_request_avg
      expr: avg_over_time(namespace_cpu_requests[1h])
    - record: namespace_memory_requests_avg_gb
      expr: avg_over_time(namespace_memory_requests[1h]) / 1024 / 1024 / 1024
    - record: namespace_memory_usage_avg_gb
      expr: avg_over_time(namespace_memory_usage[1h]) / 1024 / 1024 / 1024