---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    release: prometheus
    app: prometheus-operator
  name: opswatch.cloudfoundation.rules
  namespace: monitoring
spec:
  groups:
  - name: cloudfoundation.rules  # TODO: add ControlTower rule
    rules:
    - record: aws_cloudwatch_CloudFoundation_GuardDutyStatus_Active_Account
      expr: (max_over_time(aws_cloudwatch_CloudFoundation_GuardDutyStatus_Account_OrganizationId_Status[4h]) and on(dimension_Account) (max_over_time(aws_cloudwatch_CloudFoundation_OrganizationMemberStatus_Account_OrganizationId_Status{dimension_Status="ACTIVE"}[4h]) >= 1))
    - record: aws_cloudwatch_CloudFoundation_CloudTrailStatus_Active_Account
      expr: (max_over_time(aws_cloudwatch_CloudFoundation_CloudTrailStatus_Account_OrganizationId[4h])) and on(dimension_Account) (max_over_time(aws_cloudwatch_CloudFoundation_OrganizationMemberStatus_Account_OrganizationId_Status{dimension_Status="ACTIVE"}[4h]) >= 1)
    - record: CloudFoundationSLA
      expr: sum by (dimension_OrganizationId, asy_component) (aws_cloudwatch_CloudFoundation_GuardDutyStatus_Active_Account{dimension_Status!="Enabled"}) + sum by (dimension_OrganizationId, asy_component) (1 - aws_cloudwatch_CloudFoundation_CloudTrailStatus_Active_Account)
    - alert: CloudFoundationGuardDutyStatusNotEnabled
      annotations:
        summary: Status of GuardDuty is not enabled
        description: Status GuardDuty in account {{ $labels.dimension_Account }} and organization {{ $labels.dimension_OrganizationId }} is {{ $labels.dimension_Status }}
      expr: count(aws_cloudwatch_CloudFoundation_GuardDutyStatus_Active_Account{dimension_Status!="Enabled"}) > 0
      for: 15m
      labels:
        rule_source: opswatch-prometheus-rules
        severity: warning
        alarm_scope: INTERNAL
    - alert: CloudFoundationCloudTrailNotLogging
      annotations:
        summary: CloudTrail is not lgging
        description: CloudTrail in account {{ $labels.dimension_Account }} and organization {{ $labels.dimension_OrganizationId }} is not logging
      expr: aws_cloudwatch_CloudFoundation_CloudTrailStatus_Active_Account < 1
      labels:
        rule_source: opswatch-prometheus-rules
        severity: warning
        alarm_scope: INTERNAL
    - alert: CloudFoundationSecurityHubNotEnabled
      annotations:
        summary: SecurityHub is not enabled
        description: Member status SecurityHub in account {{ $labels.dimension_Account }} and organization {{ $labels.dimension_OrganizationId }} is {{ $labels.dimension_MemberStatus }}. Policy association status is {{ $labels.dimension_PolicyAssociationStatus}}
      expr: ((max_over_time(aws_cloudwatch_CloudFoundation_SecurityHubStatus_Account_MemberStatus_OrganizationId_PolicyAssociationStatus{dimension_MemberStatus!~"Master|Enabled"}[4h]) >= 1 or on(dimension_Account) max_over_time(aws_cloudwatch_CloudFoundation_SecurityHubStatus_Account_MemberStatus_OrganizationId_PolicyAssociationStatus{dimension_PolicyAssociationStatus!="SUCCESS"}[4h]) >= 1)) and on(dimension_Account) (max_over_time(aws_cloudwatch_CloudFoundation_OrganizationMemberStatus_Account_OrganizationId_Status{dimension_Status="ACTIVE"}[4h]) >= 1)
      for: 15m
      labels:
        rule_source: opswatch-prometheus-rules
        severity: info  # TODO: desired not enabled in many accounts warning
        alarm_scope: INTERNAL
