apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    release: prometheus
    app: prometheus-operator
  name: opswatch.elasticache.rules
  namespace: monitoring
spec:
  groups:
  - name: elasticache.rules
    rules:
    - alert: AwsCloudwatchElastiCacheCPUUtilization
      annotations:
        summary: ElastiCache has CPU Utilization higher than 90 percent
        description: ElastiCache {{ $labels.dimension_CacheClusterId }} has {{$value}}% CPU Utilization in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}
        runbook_url: https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/ErrorMessages.html
      expr: round(aws_cloudwatch_ElastiCache_CPUUtilization_CacheClusterId_CacheNodeId) > 90
      for: 60m
      labels:
        rule_source: opswatch-prometheus-rules
        severity: warning
    - alert: AwsCloudwatchElastiCacheAuthenticationFailures
      annotations:
        summary: ElastiCache has Authentication Failures higher than 3
        description: ElastiCache {{ $labels.dimension_CacheClusterId }} has {{$value}} Authentication Failures in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}
        runbook_url: https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/ErrorMessages.html
      expr: aws_cloudwatch_ElastiCache_AuthenticationFailures_CacheClusterId > 3
      for: 15m
      labels:
        rule_source: opswatch-prometheus-rules
        severity: warning
    - alert: AwsCloudwatchElastiCacheCPUCreditBalance
      annotations:
        summary: ElastiCache has CPUCreditBalance below 10
        description: ElastiCache CPU Credit balance is at {{$value}} for instance {{ $labels.dimension_CacheNodeId }} in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}
        runbook_url: https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/ErrorMessages.html
      expr: aws_cloudwatch_ElastiCache_CPUCreditBalance_CacheClusterId_CacheNodeId < 10
      for: 15m
      labels:
        rule_source: opswatch-prometheus-rules
        severity: critical
    - alert: AwsCloudwatchElastiCacheCPUCreditBalancePrediction
      annotations:
        summary: ElastiCache CPU Credit balance will be below 10 in 2 hours
        description: ElastiCache CPU Credit balance will be at {{$value}} for instance {{ $labels.dimension_CacheNodeId }} in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}
        runbook_url: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/burstable-credits-baseline-concepts.html
      labels:
        rule_source: opswatch-prometheus-rules
        severity: warning
      expr: round(predict_linear(aws_cloudwatch_ElastiCache_CPUCreditBalance_CacheClusterId_CacheNodeId[30m], 3600 * 2)) < 10
      for: 30m
    - alert: AwsCloudwatchElastiCacheCacheHitRate
      annotations:
        summary: ElastiCache has CacheHitRate below 10 percent
        description: ElastiCache {{ $labels.dimension_CacheClusterId }} has CacheHitRate of {{$value}}% in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}
        runbook_url: https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/ErrorMessages.html
      expr: aws_cloudwatch_ElastiCache_CacheHitRate_CacheClusterId < 10
      for: 30m
      labels:
        rule_source: opswatch-prometheus-rules
        severity: info
    - alert: AwsCloudwatchElastiCacheDatabaseMemoryUsageCountedForEvictPercentage
      annotations:
        summary: ElastiCache has DatabaseMemoryUsage Counted for Evict percentage above 85 percent
        description: ElastiCache {{ $labels.dimension_CacheClusterId }} has Memory Usage Counted for Evict Percentage of {{$value}}% in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}
        runbook_url: https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/ErrorMessages.html
      expr: aws_cloudwatch_ElastiCache_DatabaseMemoryUsageCountedForEvictPercentage > 85
      for: 15m
      labels:
        rule_source: opswatch-prometheus-rules
        severity: warning

    # aws_cloudwatch_ElastiCache_DatabaseMemoryUsageCountedForEvictPercentage_ReplicationGroupId
    # aws_cloudwatch_ElastiCache_DatabaseMemoryUsageCountedForEvictPercentage_NodeGroupId_ReplicationGroupId

    # #???
    # aws_cloudwatch_ElastiCache_DatabaseMemoryUsagePercentage_CacheClusterId_CacheNodeId
