apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    release: prometheus
    app: prometheus-operator
  name: opswatch.elasticsearch.rules
  namespace: monitoring
spec:
  groups:
    - name: elasticsearch.rules
      rules:
        - alert: AwsCloudwatchElasticSearchFilesystemDataFreePercent
          annotations:
            summary: ElasticSearch Free Storage Space below 10GB
            description: ElasticSearch Free Storage Space is {{$value}}GB for domain {{ $labels.dimension_DomainName }} in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}
            runbook_url: https://docs.aws.amazon.com/opensearch-service/latest/developerguide/handling-errors.html
          expr: (((aws_cloudwatch_ES_FreeStorageSpace_ClientId_DomainName * (increase(aws_cloudwatch_ES_FreeStorageSpace_ClientId_DomainName_count[60m]) / 60 * 5)) / 1024) * 60/300) < 10
          for: 15m
          labels:
            severity: critical
            asy_itsm_severity: high
        - alert: AwsCloudwatchElasticSearchHealthStatusRed
          annotations:
            summary: ElasticSearch Health Status is RED
            description: ElasticSearch Cluster Health Status is {{$value}}% for domain {{ $labels.dimension_DomainName }} in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}
            runbook_url: https://docs.aws.amazon.com/opensearch-service/latest/developerguide/handling-errors.html
          expr: aws_cloudwatch_ES_ClusterStatusred_ClientId_DomainName > 1
          for: 15m
          labels:
            severity: critical
            asy_itsm_severity: high
        - alert: AwsCloudwatchElasticSearchHealthStatusYellow
          annotations:
            summary: ElasticSearch Health Status is YELLOW
            description: ElasticSearch Cluster Health Status is {{$value}}% for domain {{ $labels.dimension_DomainName }} in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}
            runbook_url: https://docs.aws.amazon.com/opensearch-service/latest/developerguide/handling-errors.html
          expr: aws_cloudwatch_ES_ClusterStatusyellow_ClientId_DomainName > 1
          for: 15m
          labels:
            severity: critical
            asy_itsm_severity: medium
        - alert: AwsCloudwatchElasticSearchHealthUnassignedShards
          annotations:
            summary: ElasticSearch Health Status Unassigned Shards
            description: ElasticSearch Cluster Health Unassigned Shards Status is {{$value}} for domain {{ $labels.dimension_DomainName }} in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}
            runbook_url: https://docs.aws.amazon.com/opensearch-service/latest/developerguide/handling-errors.html
          expr: aws_cloudwatch_ES_Shardsunassigned_ClientId_DomainName > 0
          for: 15m
          labels:
            severity: warning
        - alert: AwsCloudwatchElasticSearchHealthRelocatingShards
          annotations:
            summary: ElasticSearch Health Status Relocating Shards
            description: ElasticSearch Cluster Health Relocating Shards Status is {{$value}} for ElasticSearch {{ $labels.dimension_DomainName }} in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}
            runbook_url: https://docs.aws.amazon.com/opensearch-service/latest/developerguide/handling-errors.html
          expr: aws_cloudwatch_ES_Shardsrelocating_ClientId_DomainName > 0
          for: 15m
          labels:
            severity: warning
        - alert: AwsCloudwatchElasticSearchHealthActiveShards
          annotations:
            summary: ElasticSearch Health Actice Shards Status is below 1
            description: ElasticSearch Cluster Active Shards Status is {{$value}} for domain {{ $labels.dimension_DomainName }} in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}
            runbook_url: https://docs.aws.amazon.com/opensearch-service/latest/developerguide/handling-errors.html
          expr: aws_cloudwatch_ES_Shardsactive_ClientId_DomainName < 1
          for: 15m
          labels:
            severity: warning
        - alert: AwsCloudwatchElasticSearchCPUUtil
          annotations:
            summary: ElasticSearch CPU Utilization is above 90 percent
            description: ElasticSearch Cluster CPU Utilization is above {{$value}}% for domain {{ $labels.dimension_DomainName }} in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}
            runbook_url: https://docs.aws.amazon.com/opensearch-service/latest/developerguide/handling-errors.html
          expr: aws_cloudwatch_ES_CPUUtilization_ClientId_DomainName > 90
          for: 15m
          labels:
            severity: warning
        - alert: AwsCloudwatchElasticSearch345xxErrorCount
          annotations:
            summary: AwsCloudwatchElasticSearch345xxErrorCount is above 100
            description: ElasticSearch Cluster Connection Error Count is {{$value}} for domain {{ $labels.dimension_DomainName }} in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}
            runbook_url: https://docs.aws.amazon.com/opensearch-service/latest/developerguide/handling-errors.html
          expr: (aws_cloudwatch_ES_3xx_ClientId_DomainName > 100) OR (aws_cloudwatch_ES_4xx_ClientId_DomainName > 100) OR (aws_cloudwatch_ES_5xx_ClientId_DomainName > 100)
          for: 15m
          labels:
            severity: warning
        - alert: AwsCloudwatchElasticSearchAutomatedSnapshotErrorCount
          annotations:
            summary: AwsCloudwatchElasticSearchAutomatedSnapshotErrorCount is greater than 2
            description: ElasticSearch Cluster Automated Snapshot Error Count is {{$value}} for domain {{ $labels.dimension_DomainName }} in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}
            runbook_url: https://docs.aws.amazon.com/opensearch-service/latest/developerguide/handling-errors.html
          expr: aws_cloudwatch_ES_AutomatedSnapshotFailure_ClientId_DomainName > 2
          for: 15m
          labels:
            severity: warning
# TODO: Check nodes degraded from sensu saas?