apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    release: prometheus
    app: prometheus-operator
  name: opswatch.mq.rules
  namespace: monitoring
spec:
  groups:
  - name: mq.queue.rules
    rules:
    - alert: AwsCloudwatchMQQueueLengthWarning
      annotations:
        summary: MQ queue length is above 1000
        description: MQ queue {{ $labels.dimensions_Queue }} has {{$value}} open items for MQ Broker {{ $labels.dimensions_Broker }} in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}.
      expr: round(aws_cloudwatch_AmazonMQ_QueueSize_Broker_Queue) > 1000
      for: 30m
      labels:
        rule_source: opswatch-prometheus-rules
        severity: info
    - alert: AwsCloudwatchMQQueueLengthCritical
      annotations:
        summary: MQ queue length is above 10000
        description: MQ queue {{ $labels.dimensions_Queue }} has {{$value}} open items for MQ Broker {{ $labels.dimensions_Broker }} in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}.
      expr: round(aws_cloudwatch_AmazonMQ_QueueSize_Broker_Queue) > 10000
      for: 30m
      labels:
        rule_source: opswatch-prometheus-rules
        severity: warning
  - name: mq.storage.rules
    rules:
    # JournalFilledOpenTransactions (https://github.com/arvatoaws-labs/activemq-xa-cli)
    - alert: AwsCloudwatchMQJournalWarning
      annotations:
        summary: MQ Journal is above 100 open files
        description: MQ Journal has {{$value}} files for MQ Broker {{ $labels.dimensions_Broker }} in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}. Consider rollbacking or committing open XA transactions.
      expr: round(aws_cloudwatch_AmazonMQ_JournalFilesForFullRecovery_Broker + aws_cloudwatch_AmazonMQ_JournalFilesForFastRecovery_Broker) > 100
      for: 30m
      labels:
        rule_source: opswatch-prometheus-rules
        severity: info
    - alert: AwsCloudwatchMQJournalCritical
      annotations:
        summary: MQ Journal is above 400 open files
        description: MQ Journal has {{$value}} files for MQ Broker {{ $labels.dimensions_Broker }} in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}. Consider rollbacking or committing open XA transactions.
      expr: round(aws_cloudwatch_AmazonMQ_JournalFilesForFullRecovery_Broker + aws_cloudwatch_AmazonMQ_JournalFilesForFastRecovery_Broker) > 400
      for: 30m
      labels:
        rule_source: opswatch-prometheus-rules
        severity: warning
    # StoragePercentUsage
    - alert: AwsCloudwatchMQStoragePercentUsageWarning
      annotations:
        summary: MQ Storage Utilizatiom is above 90 percent
        description: MQ Storage Utilizatiom is {{$value}}% for MQ Broker {{ $labels.dimensions_Broker }} in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}
      expr: round(aws_cloudwatch_AmazonMQ_StoragePercentUsage_Broker) > 90
      for: 30m
      labels:
        rule_source: opswatch-prometheus-rules
        severity: warning
    - alert: AwsCloudwatchMQStoragePercentUsageCritical
      annotations:
        summary: MQ Storage Utilizatiom is above 95 percent
        description: MQ Storage Utilizatiom is {{$value}}% for MQ Broker {{ $labels.dimensions_Broker }} in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}
      expr: round(aws_cloudwatch_AmazonMQ_StoragePercentUsage_Broker) > 95
      for: 15m
      labels:
        rule_source: opswatch-prometheus-rules
        severity: critical
  - name: mq.cpu.rules
    rules:
    # CpuUtilization
    - alert: AwsCloudwatchMQCpuUtilizationWarning
      annotations:
        summary: MQ CPU Utilizatiom is above 90 percent
        description: MQ CPU Utilizatiom is {{$value}}% for MQ Broker {{ $labels.dimensions_Broker }} in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}
      expr: round(aws_cloudwatch_AmazonMQ_CpuUtilization_Broker) > 90
      for: 30m
      labels:
        rule_source: opswatch-prometheus-rules
        severity: warning
    - alert: AwsCloudwatchMQCpuUtilizationCritical
      annotations:
        summary: MQ CPU Utilizatiom is above 95 percent
        description: MQ CPU Utilizatiom is {{$value}}% for MQ Broker {{ $labels.dimensions_Broker }} in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}
      expr: round(aws_cloudwatch_AmazonMQ_CpuUtilization_Broker) > 95
      for: 15m
      labels:
        severity: critical
    # BurstBalance
    - alert: AwsCloudwatchMQBurstBalanceCritical
      annotations:
        summary: MQ burst balance is below 10%
        description: MQ burst balance is at {{$value}}% for MQ broker {{ $labels.dimension_Broker }} in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}
      labels:
        rule_source: opswatch-prometheus-rules
        severity: critical
      expr: round(aws_cloudwatch_AmazonMQ_BurstBalance_Broker) < 10
      for: 30m
    - alert: AwsCloudwatchMQBurstBalancePrediction
      annotations:
        summary: MQ burst balance will be below 10% in 2 hours
        description: MQ burst balance will at {{$value}}% for MQ broker {{ $labels.dimension_Broker }} in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}
      labels:
        rule_source: opswatch-prometheus-rules
        severity: warning
      expr: round(predict_linear(aws_cloudwatch_AmazonMQ_BurstBalance_Broker[30m], 3600 * 2)) < 10
      for: 30m
  - name: mq.memory.rules
    rules:
    # HeapUsage (Percent) (85% normal)
    - alert: AwsCloudwatchMQHeapUsageWarning
      annotations:
        summary: MQ Heap Utilizatiom is above 90 percent
        description: MQ Heap Utilizatiom is {{$value}}% for MQ Broker {{ $labels.dimensions_Broker }} in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}
      expr: round(aws_cloudwatch_AmazonMQ_HeapUsage_Broker) > 90
      for: 30m
      labels:
        rule_source: opswatch-prometheus-rules
        severity: warning
    - alert: AwsCloudwatchMQHeapUsageCritical
      annotations:
        summary: MQ Heap Utilizatiom is above 95 percent
        description: MQ Heap Utilizatiom is {{$value}}% for MQ Broker {{ $labels.dimensions_Broker }} in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}
      expr: round(aws_cloudwatch_AmazonMQ_HeapUsage_Broker) > 95
      for: 15m
      labels:
        rule_source: opswatch-prometheus-rules
        severity: critical
  - name: mq.connections.rules
    rules:
    # CurrentConnectionsCount / (AmqpMaximumConnections or MqttMaximumConnections or OpenwireMaximumConnections or StompMaximumConnections or WsMaximumConnections)
    - alert: AwsCloudwatchMQAmqpConnectionPercentUsageCritical
      annotations:
        summary: MQ AMQP connections are above 95 percent
        description: MQ connection usage is {{$value}}% for MQ Broker {{ $labels.dimension_Broker }} in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}
      expr: round(100 * aws_cloudwatch_AmazonMQ_CurrentConnectionsCount_Broker / aws_cloudwatch_AmazonMQ_AmqpMaximumConnections_Broker) > 95
      for: 15m
      labels:
        rule_source: opswatch-prometheus-rules
        severity: critical
    - alert: AwsCloudwatchMQMqttConnectionPercentUsageCritical
      annotations:
        summary: MQ MQTT connections are above 95 percent
        description: MQ connection usage is {{$value}}% for MQ Broker {{ $labels.dimension_Broker }} in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}
      expr: round(100 * aws_cloudwatch_AmazonMQ_CurrentConnectionsCount_Broker / aws_cloudwatch_AmazonMQ_MqttMaximumConnections_Broker) > 95
      for: 15m
      labels:
        rule_source: opswatch-prometheus-rules
        severity: critical
    - alert: AwsCloudwatchMQOpenwireConnectionPercentUsageCritical
      annotations:
        summary: MQ Openwire connections are above 95 percent
        description: MQ connection usage is {{$value}}% for MQ Broker {{ $labels.dimension_Broker }} in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}
      expr: round(100 * aws_cloudwatch_AmazonMQ_CurrentConnectionsCount_Broker / aws_cloudwatch_AmazonMQ_OpenwireMaximumConnections_Broker) > 95
      for: 15m
      labels:
        rule_source: opswatch-prometheus-rules
        severity: critical
    - alert: AwsCloudwatchMQStompConnectionPercentUsageCritical
      annotations:
        summary: MQ Stomp connections are above 95 percent
        description: MQ connection usage is {{$value}}% for MQ Broker {{ $labels.dimension_Broker }} in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}
      expr: round(100 * aws_cloudwatch_AmazonMQ_CurrentConnectionsCount_Broker / aws_cloudwatch_AmazonMQ_StompMaximumConnections_Broker) > 95
      for: 15m
      labels:
        rule_source: opswatch-prometheus-rules
        severity: critical
    - alert: AwsCloudwatchMQWsConnectionPercentUsageCritical
      annotations:
        summary: MQ WS connections are above 95 percent
        description: MQ connection usage is {{$value}}% for MQ Broker {{ $labels.dimension_Broker }} in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}
      expr: round(100 * aws_cloudwatch_AmazonMQ_CurrentConnectionsCount_Broker / aws_cloudwatch_AmazonMQ_WsMaximumConnections_Broker) > 95
      for: 15m
      labels:
        rule_source: opswatch-prometheus-rules
        severity: critical
    - alert: AwsCloudwatchMQAmqpConnectionPercentUsageWarning
      annotations:
        summary: MQ AMQP connections are above 80 percent
        description: MQ connection usage is {{$value}}% for MQ Broker {{ $labels.dimension_Broker }} in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}
      expr: round(100 * aws_cloudwatch_AmazonMQ_CurrentConnectionsCount_Broker / aws_cloudwatch_AmazonMQ_AmqpMaximumConnections_Broker) > 80
      for: 15m
      labels:
        rule_source: opswatch-prometheus-rules
        severity: warning
    - alert: AwsCloudwatchMQMqttConnectionPercentUsageWarning
      annotations:
        summary: MQ MQTT connections are above 80 percent
        description: MQ connection usage is {{$value}}% for MQ Broker {{ $labels.dimension_Broker }} in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}
      expr: round(100 * aws_cloudwatch_AmazonMQ_CurrentConnectionsCount_Broker / aws_cloudwatch_AmazonMQ_MqttMaximumConnections_Broker) > 80
      for: 15m
      labels:
        rule_source: opswatch-prometheus-rules
        severity: warning
    - alert: AwsCloudwatchMQOpenwireConnectionPercentUsageWarning
      annotations:
        summary: MQ Openwire connections are above 80 percent
        description: MQ connection usage is {{$value}}% for MQ Broker {{ $labels.dimension_Broker }} in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}
      expr: round(100 * aws_cloudwatch_AmazonMQ_CurrentConnectionsCount_Broker / aws_cloudwatch_AmazonMQ_OpenwireMaximumConnections_Broker) > 80
      for: 15m
      labels:
        rule_source: opswatch-prometheus-rules
        severity: warning
    - alert: AwsCloudwatchMQStompConnectionPercentUsageWarning
      annotations:
        summary: MQ Stomp connections are above 80 percent
        description: MQ connection usage is {{$value}}% for MQ Broker {{ $labels.dimension_Broker }} in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}
      expr: round(100 * aws_cloudwatch_AmazonMQ_CurrentConnectionsCount_Broker / aws_cloudwatch_AmazonMQ_StompMaximumConnections_Broker) > 80
      for: 15m
      labels:
        rule_source: opswatch-prometheus-rules
        severity: warning
    - alert: AwsCloudwatchMQWsConnectionPercentUsageWarning
      annotations:
        summary: MQ WS connections are above 80 percent
        description: MQ connection usage is {{$value}}% for MQ Broker {{ $labels.dimension_Broker }} in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}
      expr: round(100 * aws_cloudwatch_AmazonMQ_CurrentConnectionsCount_Broker / aws_cloudwatch_AmazonMQ_WsMaximumConnections_Broker) > 80
      for: 15m
      labels:
        rule_source: opswatch-prometheus-rules
        severity: warning