apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    release: prometheus
    app: prometheus-operator
  name: opswatch.rds.rules
  namespace: monitoring
spec:
  groups:
  - name: rds.rules
    rules:
    # https://aws.amazon.com/de/blogs/database/part1-best-practices-on-how-to-configure-monitoring-and-alerts-for-amazon-rds-for-sql-server/
    - alert: AwsCloudwatchRdsDDLLatencyWarning
      annotations:
        summary: RDS DDLLatency is greater than 20ms
        description: RDS DDLLatency latency is {{$value}}ms for DB instance {{ $labels.dimension_DBInstanceIdentifier }} in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}
      expr: round(aws_cloudwatch_RDS_DDLLatency_DBInstanceIdentifier) > 20
      for: 15m
      labels:
        severity: warning
    - alert: AwsCloudwatchRdsDDLLatencyCritical
      annotations:
        summary: RDS DDLLatency is greater than 50ms
        description: RDS DDLLatency latency is {{$value}}ms for DB instance {{ $labels.dimension_DBInstanceIdentifier }} in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}
      expr: round(aws_cloudwatch_RDS_DDLLatency_DBInstanceIdentifier) > 50
      for: 15m
      labels:
        severity: critical
    - alert: AwsCloudwatchRdsReadLatencyWarning
      annotations:
        summary: RDS ReadLatency is greater than 20ms
        description: RDS ReadLatency is {{$value}}ms for DB instance {{ $labels.dimension_DBInstanceIdentifier }} in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}
      expr: round(aws_cloudwatch_RDS_ReadLatency_DBInstanceIdentifier) > 20
      for: 15m
      labels:
        severity: warning
    - alert: AwsCloudwatchRdsReadLatencyCritical
      annotations:
        summary: RDS ReadLatency is greater than 50ms
        description: RDS ReadLatency is {{$value}}ms for DB instance {{ $labels.dimension_DBInstanceIdentifier }} in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}
      expr: round(aws_cloudwatch_RDS_ReadLatency_DBInstanceIdentifier) > 50
      for: 15m
      labels:
        severity: critical
    - alert: AwsCloudwatchRdsWriteLatencyWarning
      annotations:
        summary: RDS WriteLatency is greater than 20ms
        description: RDS DDLLatency latency is {{$value}}ms for DB instance {{ $labels.dimension_DBInstanceIdentifier }} in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}
      expr: round(aws_cloudwatch_RDS_WriteLatency_DBInstanceIdentifier) > 20
      for: 15m
      labels:
        severity: warning
    - alert: AwsCloudwatchRdsWriteLatencyCritical
      annotations:
        summary: RDS WriteLatency is greater than 50ms
        description: RDS WriteLatency is {{$value}}ms for DB instance {{ $labels.dimension_DBInstanceIdentifier }} in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}
      expr: round(aws_cloudwatch_RDS_WriteLatency_DBInstanceIdentifier) > 50
      for: 15m
      labels:
        severity: critical
    - alert: AwsCloudwatchRdsDeleteLatencyyWarning
      annotations:
        summary: RDS DeleteLatency is greater than 20ms
        description: RDS DeleteLatency is {{$value}}ms for DB instance {{ $labels.dimension_DBInstanceIdentifier }} in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}
      expr: round(aws_cloudwatch_RDS_DeleteLatency_DBInstanceIdentifier) > 20
      for: 15m
      labels:
        severity: warning
    - alert: AwsCloudwatchRdsDeleteLatencyCritical
      annotations:
        summary: RDS DeleteLatency is greater than 50ms
        description: RDS DeleteLatency is {{$value}}ms for DB instance {{ $labels.dimension_DBInstanceIdentifier }} in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}
      expr: round(aws_cloudwatch_RDS_DeleteLatency_DBInstanceIdentifier) > 50
      for: 15m
      labels:
        severity: critical
    - alert: AwsCloudwatchRdsUpdateLatencyWarning
      annotations:
        summary: RDS UpdateLatency is greater than 20ms
        description: RDS UpdateLatency is {{$value}}ms for DB instance {{ $labels.dimension_DBInstanceIdentifier }} in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}
      expr: round(aws_cloudwatch_RDS_UpdateLatency_DBInstanceIdentifier) > 20
      for: 15m
      labels:
        severity: warning
    - alert: AwsCloudwatchRdsUpdateLatencyCritical
      annotations:
        summary: RDS UpdateLatency is greater than 50ms
        description: RDS UpdateLatency is {{$value}}ms for DB instance {{ $labels.dimension_DBInstanceIdentifier }} in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}
      expr: round(aws_cloudwatch_RDS_UpdateLatency_DBInstanceIdentifier) > 50
      for: 15m
      labels:
        severity: critical
    - alert: AwsCloudwatchRdsCommitLatencyWarningSingleAz
      annotations:
        summary: RDS CommitLatency is greater than 20ms (single az)
        description: RDS CommitLatency is {{$value}}ms for DB instance {{ $labels.dimension_DBInstanceIdentifier }} in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}
      expr: round(aws_cloudwatch_RDS_CommitLatency_DBInstanceIdentifier{rds_engine!~".*aurora.*",rds_db_multi_az="false"}) > 20
      for: 15m
      labels:
        severity: warning
    - alert: AwsCloudwatchRdsCommitLatencyWarningMultiAz
      annotations:
        summary: RDS CommitLatency is greater than 30ms (multi az)
        description: RDS CommitLatency is {{$value}}ms for DB instance {{ $labels.dimension_DBInstanceIdentifier }} in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}
      expr: round(aws_cloudwatch_RDS_CommitLatency_DBInstanceIdentifier{rds_engine!~".*aurora.*",rds_db_multi_az="true"}) > 30
      for: 15m
      labels:
        severity: warning
    - alert: AwsCloudwatchRdsCommitLatencyWarningAurora
      annotations:
        summary: RDS CommitLatency is greater than 60ms (aurora)
        description: RDS CommitLatency is {{$value}}ms for DB instance {{ $labels.dimension_DBInstanceIdentifier }} in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}
      expr: round(aws_cloudwatch_RDS_CommitLatency_DBInstanceIdentifier{rds_engine=~".*aurora.*"}) > 60
      for: 15m
      labels:
        severity: warning
    - alert: AwsCloudwatchRdsDDLLatencyWarning
      annotations:
        summary: RDS CommitLatency is greater than 20ms
        description: RDS CommitLatency is {{$value}}ms for DB instance {{ $labels.dimension_DBInstanceIdentifier }} in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}
      expr: round(aws_cloudwatch_RDS_CommitLatency_DBInstanceIdentifier) > 20
      for: 15m
      labels:
        severity: critical
    - alert: AwsCloudwatchRdsBurstBalanceCritical
      annotations:
        summary: RDS burst balance is below 10%
        description: RDS burst balance is at {{$value}}% for DB instance {{ $labels.dimension_DBInstanceIdentifier }} in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}
        runbook_url: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/burstable-credits-baseline-concepts.html
      labels:
        severity: critical
        asy_itsm_severity: high
      expr: round(aws_cloudwatch_RDS_BurstBalance_DBInstanceIdentifier) < 10
      for: 30m
    - alert: AwsCloudwatchRdsBurstBalancePrediction
      annotations:
        summary: RDS burst balance will be below 10% in 2 hours
        description: RDS burst balance will at {{$value}}% for DB instance {{ $labels.dimension_DBInstanceIdentifier }} in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}
        runbook_url: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/burstable-credits-baseline-concepts.html
      labels:
        severity: critical
        asy_itsm_severity: medium
      expr: round(predict_linear(aws_cloudwatch_RDS_BurstBalance_DBInstanceIdentifier[30m], 3600 * 2)) < 10
      for: 30m
    - alert: AwsCloudwatchRdsCPUCreditBalanceCritical
      annotations:
        summary: RDS CPU Credit balance is below 10
        description: RDS CPU Credit balance is at {{$value}} for DB instance {{ $labels.dimension_DBInstanceIdentifier }} in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}
        runbook_url: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/burstable-credits-baseline-concepts.html
      labels:
        severity: critical
      expr: round(aws_cloudwatch_RDS_CPUCreditBalance_DBInstanceIdentifier) < 10
      for: 30m
    - alert: AwsCloudwatchRdsCPUCreditBalancePrediction
      annotations:
        summary: RDS CPU Credit balance will be below 10 in 2 hours
        description: RDS Credit balance will at {{$value}} for DB instance {{ $labels.dimension_DBInstanceIdentifier }} in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}
        runbook_url: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/burstable-credits-baseline-concepts.html
      labels:
        severity: warning
      expr: round(predict_linear(aws_cloudwatch_RDS_CPUCreditBalance_DBInstanceIdentifier[30m], 3600 * 2)) < 10
      for: 30m
    - alert: AwsCloudwatchRDSCPUUtilizationHigh
      annotations:
        summary: RDS CPU utlization greater than 90%
        description: RDS CPU utlization at {{$value}}% for DB instance {{ $labels.dimension_DBInstanceIdentifier }} in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}
      labels:
        severity: warning
      expr: round(aws_cloudwatch_RDS_CPUUtilization_DBInstanceIdentifier) > 90
      for: 30m
    - alert: AwsCloudwatchRdsEBSByteCreditBalanceCritical
      annotations:
        summary: RDS EBS Byte Credit balance is low below 10
        description: RDS EBS Byte Credit balance is at {{$value}} for DB instance {{ $labels.dimension_DBInstanceIdentifier }} in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}
        runbook_url: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/burstable-credits-baseline-concepts.html
      labels:
        severity: critical
      expr: aws_cloudwatch_RDS_EBSByteBalance_DBInstanceIdentifier{rds_engine!~".*aurora.*"}  < 10
      for: 30m
    - alert: AwsCloudwatchRdsEBSByteCreditBalancePrediction
      annotations:
        summary: RDS EBS Byte Credit balance will be below 10 in 2 hours
        description: RDS EBS Byte Credit balance will at {{$value}} for DB instance {{ $labels.dimension_DBInstanceIdentifier }} in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}
        runbook_url: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/burstable-credits-baseline-concepts.html
      labels:
        severity: warning
      expr: round(predict_linear(aws_cloudwatch_RDS_EBSByteBalance_DBInstanceIdentifier{rds_engine!~".*aurora.*"}[30m], 3600 * 2)) < 10
      for: 30m
    - alert: AwsCloudwatchRdsEBSIOCreditBalanceCritical
      annotations:
        summary: RDS EBS IO Credit balance is below 10
        description: RDS EBS IO Credit balance is at {{$value}} for DB instance {{ $labels.dimension_DBInstanceIdentifier }} in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}
        runbook_url: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/burstable-credits-baseline-concepts.html
      labels:
        severity: critical
      expr: aws_cloudwatch_RDS_EBSIOBalance_DBInstanceIdentifier < 10
      for: 30m
    - alert: AwsCloudwatchRdsEBSIOCreditBalancePrediction
      annotations:
        summary: RDS EBS IO Credit balance will be below 10 in 2 hours
        description: RDS EBS IO Credit balance will at {{$value}} for DB instance {{ $labels.dimension_DBInstanceIdentifier }} in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}
        runbook_url: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/burstable-credits-baseline-concepts.html
      labels:
        severity: warning
      expr: round(predict_linear(aws_cloudwatch_RDS_EBSIOBalance_DBInstanceIdentifier[30m], 3600 * 2)) < 10
      for: 30m
    - alert: AwsCloudwatchRdsDeadlocks
      annotations:
        summary: RDS reports deadlocks
        description: RDS reports {{$value}} deadlocks for DB instance {{ $labels.dimension_DBInstanceIdentifier }} in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}
      expr: aws_cloudwatch_RDS_Deadlocks_DBInstanceIdentifier > 0
      for: 15m
      labels:
        severity: warning
    - alert: AwsCloudwatchRdsAbortedClients
      annotations:
        summary: RDS reports aborted clients
        description: RDS reports {{$value}} aborted clients for DB instance {{ $labels.dimension_DBInstanceIdentifier }} in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}
      expr: aws_cloudwatch_RDS_AbortedClients_DBInstanceIdentifier > 0
      for: 15m
      labels:
        severity: warning
    - alert: AwsCloudwatchRdsLoginFailures
      annotations:
        summary: RDS reports login failures
        description: RDS reports {{$value}} login failures for DB instance {{ $labels.dimension_DBInstanceIdentifier }} in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}
      expr: aws_cloudwatch_RDS_LoginFailures_DBInstanceIdentifier > 0
      for: 15m
      labels:
        severity: critical
        asy_itsm_severity: high
    - alert: AwsCloudwatchRdsAuroraReplicaLag
      annotations:
        summary: RDS aurora replica lag is more than 100ms
        description: RDS aurora replica lag is {{$value}}ms for DB instance {{ $labels.dimension_DBInstanceIdentifier }} in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}
      expr: round(aws_cloudwatch_RDS_AuroraReplicaLag_DBInstanceIdentifier) > 100
      for: 15m
      labels:
        severity: warning
    - alert: AwsCloudwatchRdsAuroraBinlogReplicaLag
      annotations:
        summary: RDS aurora binlog replica lag is more than 100ms
        description: RDS aurora binlog replica lag is {{$value}}ms for DB instance {{ $labels.dimension_DBInstanceIdentifier }} in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}
      expr: round(aws_cloudwatch_RDS_AuroraBinlogReplicaLag_DBInstanceIdentifier) > 100
      for: 15m
      labels:
        severity: warning
    - alert: AwsCloudwatchRdsFreeLocalStorage
      annotations:
        summary: RDS free local storage is less than 10GB
        description: RDS free local storage is {{$value}}GB for DB instance {{ $labels.dimension_DBInstanceIdentifier }} in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}
        runbook_url: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_Troubleshooting.html#CHAP_Troubleshooting.Storage
      expr: round(aws_cloudwatch_RDS_FreeLocalStorage) < 10
      for: 15m
      labels:
        severity: warning
    - alert: AwsCloudwatchRdsClusterMaxConnections
      annotations:
        summary: RDS connection count is more than 90%
        description: RDS connection count is {{$value}}% for DB cluster {{ $labels.dimension_DBClusterIdentifier }} in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}
        runbook_url: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_Limits.html#RDS_Limits.MaxConnections
      expr: round(aws_cloudwatch_RDS_DatabaseConnections_DBClusterIdentifier / aws_apidescribe_RDS_MaxConnections_DBClusterIdentifier * 100) > 90
      for: 15m
      labels:
        severity: critical
        asy_itsm_severity: high
    - alert: AwsCloudwatchRdsInstanceMaxConnections
      annotations:
        summary: RDS connection count is more than 90%
        description: RDS connection count is {{$value}}% for DB instance {{ $labels.dimension_DBInstanceIdentifier }} in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}
        runbook_url: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_Limits.html#RDS_Limits.MaxConnections
      expr: round(aws_cloudwatch_RDS_DatabaseConnections_DBInstanceIdentifier / aws_apidescribe_RDS_MaxConnections_DBInstanceIdentifier * 100) > 90
      for: 15m
      labels:
        severity: critical
        asy_itsm_severity: high
    - alert: AwsCloudwatchRdsInstanceACUUtilizationHigh
      annotations:
        summary: RDS ACU utilization is more than 90%
        description: RDS ACU utilization is {{$value}}% for DB instance {{ $labels.dimension_DBInstanceIdentifier }} in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}
        runbook_url: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_Limits.html#RDS_Limits.MaxConnections
      expr: round(aws_cloudwatch_RDS_ACUUtilization_DBInstanceIdentifier) > 90
      for: 15m
      labels:
        severity: warning
    - alert: AwsCloudwatchRdsClusterACUUtilizationHigh
      annotations:
        summary: RDS ACU utilization is more than 90%
        description: RDS ACU utilization is {{$value}}% for DB instance {{ $labels.dimension_DBInstanceIdentifier }} in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}
        runbook_url: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_Limits.html#RDS_Limits.MaxConnections
      expr: round(aws_cloudwatch_RDS_ACUUtilization_DBClusterIdentifier) > 90
      for: 15m
      labels:
        severity: warning
    # ggf. basierend auf engine und instance_class
    #aws_cloudwatch_RDS_ServerlessDatabaseCapacity_EngineName
# TODO: high ticket für out of memory?
# TODO: high ticket für out disk space when not autoscaling or at max autoscaling?
