apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    release: prometheus
    app: prometheus-operator
  name: opswatch.route53.rules
  namespace: monitoring
spec:
  groups:
    - name: route53.rules
      rules:
        - alert: AwsCloudwatchRoute53HealthCheckPercentageCritical
          annotations:
            summary: Route53 health check ratio is below 20%
            description: Route53 health check ratio is {{$value}}% for health check id {{ $labels.dimension_HealthCheckId }} & address {{ $labels.address }} in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}
            runbook_url: https://aws.amazon.com/de/premiumsupport/knowledge-center/route-53-fix-unhealthy-health-checks/
          expr: aws_cloudwatch_Route53_HealthCheckPercentageHealthy_HealthCheckId{disabled="false"} < 20
          for: 30m
          labels:
            severity: critical
            asy_itsm_severity: high
        - alert: AwsCloudwatchRoute53HealthCheckPercentageWarning
          annotations:
            summary: Route53 health check ratio is below 50%
            description: Route53 health check ratio is {{$value}}% for health check id {{ $labels.dimension_HealthCheckId }} & address {{ $labels.address }} in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}
            runbook_url: https://aws.amazon.com/de/premiumsupport/knowledge-center/route-53-fix-unhealthy-health-checks/
          expr: aws_cloudwatch_Route53_HealthCheckPercentageHealthy_HealthCheckId{disabled="false"} < 50
          for: 15m
          labels:
            severity: warning
