---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    release: prometheus
    app: prometheus-operator
  name: opswatch.sns.rules
  namespace: monitoring
spec:
  groups:
    - name: sns.rules
      rules:
        - alert: AwsCloudwatchSNSFailures
          annotations:
            summary: SNS delivery failures
            description: SNS topic {{ $labels.dimension_TopicName }} has {{$value}} delivery failures in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}
          expr: aws_cloudwatch_SNS_NumberOfNotificationsFailed_TopicName > 0
          for: 30m
          labels:
            rule_source: opswatch-prometheus-rules
            severity: warning
            alarm_class: REACTIVE
