---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    release: prometheus
    app: prometheus-operator
  name: opswatch.sqs.rules
  namespace: monitoring
spec:
  groups:
  - name: sqs.rules
    rules:
    - alert: AwsCloudwatchSQSCongestion
      annotations:
        summary: SQS has more than 150 unprocessed messages
        description: SQS queue {{ $labels.dimension_QueueName }} has {{$value}} messages in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}
        runbook: Ensure that SQS workers are processing messages
      expr: aws_cloudwatch_SQS_ApproximateNumberOfMessagesVisible_QueueName > 150
      for: 15m
      labels:
        severity: warning
    - alert: AwsCloudwatchSQSEmptyReceives
      annotations:
        summary: SQS has more than 100 empty receives
        description: SQS queue {{ $labels.dimension_QueueName }} has {{$value}} empty receives in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }}
        runbook: Reduction of SQS worker capacity is recommended
      expr: aws_cloudwatch_SQS_NumberOfEmptyReceives_QueueName > 100 # TODO: sensible limit value missing
      for: 15m
      labels:
        severity: warning
    - alert: AwsCloudwatchSQSOldMessages
      annotations:
        summary: SQS has messsages approaching expiration
        description: SQS queue {{ $labels.dimension_QueueName }} in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }} doesn't seem to be processing messages, as the messages are close to expiration.
      expr: predict_linear(aws_cloudwatch_SQS_ApproximateAgeOfOldestMessage_QueueName[1h], 3600) > aws_apidescribe_SQS_MessageRetentionPeriod_QueueName
      for: 15m
      labels:
        severity: warning
    - alert: AwsCloudwatchSQSDeadLetter
      annotations:
        summary: SQS dead letter queue has messages failures from other queues
        description: SQS queue {{ $labels.dimension_QueueName }} in customer {{ $labels.overwrite_asy_customer }} account {{ $labels.overwrite_aws_account_id }} region {{ $labels.overwrite_aws_region }} has message failures from other queues
      expr: aws_cloudwatch_SQS_ApproximateAgeOfOldestMessage_QueueName{dimension_QueueName=~".*(dead-let[t]?er|dlq|DLQ)(\\.fifo)?$"} > 0
      for: 15m
      labels:
        severity: critical
        asy_itsm_severity: medium
